### PR TITLE
Add different Azure Environments capability

### LINKED ISSUE #12: Latest version fails due to cross cloud requests
**Describe the bug**
In the update to use managed identities, if the subscription resides in an environment that is not the Azure public cloud (i.e. azure.com) then the `Connect-AzAccount` will fail due to a cross cloud request.

For example, I updated the script from 3.6 to 3.8. Our cloud is AzureUSGovernment. (azure.us)  

`Connect-AzAccount : ClientCertificateCredential authentication failed: AADSTS900382: Confidential Client is not supported in Cross Cloud request. `

**To Reproduce**
Run the workbook in a cloud that is not the default public cloud with a system or user-managed identity.

**Expected behavior**
Should work as expected, but you will need to specify environment.

**Additional context**
I will submit a PR shortly to resolve this issue.

### PR DESCRIPTION
**Pull request by InKahootz**
This will resolve #12 

I can also revert the last commit with the TOC change if needed. Just let me know!

### CODE REVIEW

**Comment by InKahootz** [comment]
Output log from it successfully running in our cloud

```
Mode             : Process

ContextDirectory : 

ContextFile      : 

CacheDirectory   : 

CacheFile        : 

Settings         : {}



Runbook started. Version: 3.9.0



*** Running in LIVE mode. Schedules will be enforced. ***



Current Eastern Standard Time time [Thursday, 2022 Mar 17 15:01:44] will be checked against schedules



Specified subscription name/ID: [SUBSCRIPTION_NAME]



Specified Azure Environment: [AzureUSGovernment]



Logging in to Azure using the system managed identity...



Working against subscription: <SUBSCRIPTION_NAME> (<GUID>)



Found [0] schedule-tagged resource groups in subscription



Processing [0] virtual machines found in subscription



Finished processing virtual machine schedules



Runbook finished (Duration: 00:00:15)

```

**Comment by tomasrudh** [comment]
Hello, thank you so much for your contribution, and sorry for my late reply.

I will tweak your code just a little, but definitely implement it. And also your changes to the TOC.

Thanks again!
/Tomas

**Review by tomasrudh — CHANGES_REQUESTED** [review]
On line 349, add ' -ErrorAction Ignore' at the end.

This will prevent an error message in case the variable is omitted.

/Tomas

**Comment by InKahootz** [comment]
Fixed some whitespace issues as well I didn't see. I originally made the changes inside the module editor in our automation account and didn't realize it inserted tabs instead of spaces. Trimmed off trailing whitespace as well.

**Pull request merged**
